input_data:
  - file: '/path/to/file1.root'
    histogram: 'histogram1'
    color: 'kBlue'
    marker_style: 'kFullSquare'
    marker_size: 1.5
  - file: '/path/to/file2.root'
    histogram: 'histogram2'
    color: 'kRed'
    marker_style: 'kOpenCircle'
    marker_size: 1.0

canvas:
  width: 800
  height: 600
  title: 'Title of the figure'
  margin:
    left: 0.1
    right: 0.1
    top: 0.1
    bottom: 0.1
  axes:
    x:
      label: 
        name: 'x-axis label'
        size: 0.05
        offset: 0.5
      range: [0, 10]
    y:
      label: 
        name: 'y-axis label'
        size: 0.05
        offset: 0.5
      range: [0, 100]

text:
  - content: 'Hello, this is some LaTeX text!'
    x: 0.2
    y: 0.6
    size: 0.07
  - content: 'Hello, this is some other LaTeX text!'
    x: 0.2
    y: 0.4
    size: 0.04

legend:
  draw: true
  x1: 0.7
  y1: 0.7
  x2: 0.9
  y2: 0.9
  entries:
    - histogram: 'histogram1'
      label: 'Data 1'
      style: 'l'
    - histogram: 'histogram2'
      label: 'Data 2'
      style: 'p'

horizontal_line:
  draw: true
  height: 50
  line_color: ROOT.kBlack  # Use appropriate ROOT color constant
  line_style: 9  # Use appropriate ROOT line style constant


output_file: 'output_figure.pdf'
