input_data:
  - file: '/path/to/file1.root'
    histogram: 'histogram1'
    dataframe_column: 'fM'               # Draw the histogram of the column1 of the parquet file
    selections: '2 < fPt < 4'
    color: 'kRed'
    marker_style: 'kOpenCircle'
    marker_size: 1.0
    line_width: 1
    scale_factor: 1.0
    fill_style: 3145
    fill_color: 'kRed'
    fill_alpha: 0.5
    normalize: true
    draw_option: 'hist'
  - file: '/path/to/file1.root'
    histogram: 'histogram1'
    color: 'kBlue'
    marker_style: 'kFullSquare'
    marker_size: 1.5
    line_width: 1
    scale_factor: 1.0
    fill_style: 3002
    fill_color: 'kGray+1'
    fill_alpha: 0.5
    normalize: true
    draw_option: 'e'

canvas:
  width: 800
  height: 600
  title: 'Title of the figure'
  margin:
    left: 0.1
    right: 0.1
    top: 0.1
    bottom: 0.1
  axes:
    x:
      title: 
        name: 'x-axis title'
        size: 0.05
        offset: 1
      labels:
        size: 0.045
        offset: 0.01
      range: [0, 10]
      log_scale: false
    y:
      title: 
        name: 'y-axis title'
        size: 0.05
        offset: 1
      labels:
        size: 0.045
        offset: 0.01
      range: [0, 10]
      log_scale: false

text:
  - content: 'Hello, this is some LaTeX text!'
    x: 0.2
    y: 0.6
    size: 0.07
    font: 42
  - content: 'Hello, this is some other LaTeX text!'
    x: 0.2
    y: 0.4
    size: 0.04
    font: 42

legend:
  draw: true
  x1: 0.7
  y1: 0.7
  x2: 0.9
  y2: 0.9
  size: 0.05
  entries:
    - histogram: 'histogram1'
      label: 'Data 1'
      style: 'l'
    - histogram: 'histogram2'
      label: 'Data 2'
      style: 'p'

horizontal_line:
  draw: true
  height: 50
  line_color: ROOT.kBlack  # Use appropriate ROOT color constant
  line_style: 9  # Use appropriate ROOT line style constant


output_file: 'output_figure.pdf'
