inputs:
  sparse:
    file_names: [ 
        path/to/Analysis_results.root
      ]
    axis_pt_gen: 0
    axis_npv_gen: 2
    axis_pt_reco: 1
    axis_npv_reco: 6
  task_name: 'hf-task-ds'
  cuts_file_name: 'path/to/cutset.yml'

weights:
  apply: False
  file_name: null
  reweight_on_data_events: False
  data_analysis_results: []

verbose: False
output_dir: 'path/of/output/dir'
suffix: 'suffix'