infiles:
    signal:
        prompt:
            filename: [     
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt0_2/DsPrompt_pT_0_2_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt2_4/DsPrompt_pT_2_4_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt4_6/DsPrompt_pT_4_6_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt6_8/DsPrompt_pT_6_8_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt8_12/DsPrompt_pT_8_12_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt12_24/DsPrompt_pT_12_24_ModelApplied.parquet.gzip",

                        ]
            dirname: null
            treename: null
        feeddown:
            filename: [     
                
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt0_2/DsFD_pT_0_2_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt2_4/DsFD_pT_2_4_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt4_6/DsFD_pT_4_6_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt6_8/DsFD_pT_6_8_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt8_12/DsFD_pT_8_12_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt12_24/DsFD_pT_12_24_ModelApplied.parquet.gzip",
                    ]
                       
            dirname: null
            treename: null
    secpeak: # only for Ds
        prompt:
            filename: [     
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt0_2/DplusPrompt_pT_0_2_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt2_4/DplusPrompt_pT_2_4_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt4_6/DplusPrompt_pT_4_6_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt6_8/DplusPrompt_pT_6_8_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt8_12/DplusPrompt_pT_8_12_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt12_24/DplusPrompt_pT_12_24_ModelApplied.parquet.gzip",

                        ]
            dirname: null
            treename: null
        feeddown:
            filename: [     
                
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt0_2/DplusFD_pT_0_2_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt2_4/DplusFD_pT_2_4_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt4_6/DplusFD_pT_4_6_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt6_8/DplusFD_pT_6_8_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt8_12/DplusFD_pT_8_12_ModelApplied.parquet.gzip",
                            "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt12_24/DplusFD_pT_12_24_ModelApplied.parquet.gzip",
                    ]
            dirname: null
            treename: null
        mean: 1.87 # fixed values of mean and sigma, used if histogram is not provided
        sigma: 0.008
    background:
        filename: [     
            
                        "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt0_2/Data_pT_0_2_ModelApplied.parquet.gzip",
                        "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt2_4/Data_pT_2_4_ModelApplied.parquet.gzip",
                        "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt4_6/Data_pT_4_6_ModelApplied.parquet.gzip",
                        "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt6_8/Data_pT_6_8_ModelApplied.parquet.gzip",
                        "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt8_12/Data_pT_8_12_ModelApplied.parquet.gzip",
                        "/home/fchinu/Run3/Ds_pp_13TeV/ML/Application/WoNormVariables_LHC24d3a_b/pt12_24/Data_pT_12_24_ModelApplied.parquet.gzip",
                ]
        dirname: null
        treename: null
        n_events: 2747128772 # number of events for bkg in dataframe (~85M divided by rejection factor: 1)
        fraction_to_keep: [1., 1., 1., 1., 1., 1.]
        is_mc: false # if false bkg from SB
        fit_func: expo # fit function for bkg from SB, e.g. pol1, pol2, expo
        n_sigma: 4 # number of sigma from signal region, used to select SB
        corr_factor:
            filename: null # set null if no MC bkg correction is needed
            histoname: null

    acceptance: 
        filename: /home/fchinu/Run3/Ds_pp_13TeV/Datasets/Ds_pp_run3_ml/MC/Train272355/AnalysisResults_LHC24g5.root
        axispt_gen: 0
        axispt_reco: 1

predictions:
    crosssec:
        filename: DmesonAnalysis/models/fonll/feeddown/DmesonLcPredictions_13TeV_y05_FFee_BRpythia8_SepContr_PDG2020.root
        histonames:
            ds:
                prompt: hDsPhipitoKkpipred_central
                feeddown: hDsPhipitoKkpifromBpred_central_corr
                br_corr: 1.
            dplus:
                prompt: hDpluskpipipred_central
                feeddown: hDpluskpipifromBpred_central_corr
                br_corr: 0.02867803837953092 #2.69e-3 / 9.38e-2
    raa:
        prompt: 1. # can either be a fixed value or a text file
        feeddown: 1. # can either be a fixed value or a text file
        model: 

n_expected_events: 52731740058
sigma_mb: 59.4e+9 #pb
taa: 1.

expected_signal_from: 'prompt' # Choice between: 'prompt' or 'feeddown'

bkg_corr_factor:
    filename: null # set null if no MC bkg correction is needed
    histoname: null

min_mass: [1.7, 1.7, 1.7, 1.7, 1.7, 1.7]
max_mass: [2.1, 2.1, 2.1, 2.15, 2.15, 2.15]

pt_mins: [0, 2, 4, 6, 8, 12, 24]  # list 
pt_maxs: [2, 4, 6, 8, 12, 24]  # list 

df_parameter_cuts:
    name: null 
    min: null
    max: null
    enable: false  # enable cuts over df column query over each df and relative scan histos 

cut_vars:
    ML_output_Bkg:
        min:    [0.01,  0.05,   0.05,    0.1,   0.1,     0.1] #[0.01,  0.01,   0.1,    0.1,    0.1,    0.1 ]
        max:    [0.2,   0.25,   0.25,    0.4,   0.4,    0.5] #[0.3,   0.3,    0.6,    0.6,    0.6,    0.6 ]
        steps:  [20,     20,      20,     20,    20,      20] #[51,    51,     51,     51,     51,     51]
        upper_lower_cut: upper
    ML_output_Prompt:
        min:    [0.2,  0.2,   0.2,   0.2,   0.2,   0.2] #[0.,    0.,     0.,     0.,     0.,     0. ]
        max:    [0.6,  0.6,   0.6,   0.6,   0.6,   0.6] #[0.6,   0.6,    0.6,    0.6,    0.6,    0.6 ]
        steps:  [9,     9,      9,      9,      9,      9] #[13,    13,     13,     13,     13,     13]
        upper_lower_cut: lower

working_points: # list of working points or null
    ML_output_Prompt:   [0.45,  0.45,   0.45,   0.45,  0.45,    0.45]
    ML_output_Bkg:      [0.05,  0.12,   0.14,   0.22,  0.25,    0.35]

n_workers: 30

output_dir: /home/fchinu/Run3/Ds_pp_13TeV/Optimization/output

