input_files: 
  DsPrompt: path/to/DsPrompt.parquet
  DplusPrompt: path/to/DplusPrompt.parquet
  DsFD: path/to/DsFD.parquet
  DplusFD: path/to/DplusFD.parquet

dataset_eff_frac: [0.2, 1, 0.2, 1]

analysis_result_file_prompt: path/to/AnalysisResultsPrompt.root
analysis_result_file_FD: path/to/AnalysisResultsFD.root

pt_bins:
  mins: [1,2,3]
  maxs: [2,3,4]
preselections: [null, null, null]
model_handlers: [ path/to/ModelHandler_pT_1_2.pickle,
                  path/to/ModelHandler_pT_2_3.pickle,
                  path/to/ModelHandler_pT_3_4.pickle]

output_file: "Efficiencies.root"
