inputs:
  names: [
    path/to/Analysis_results.root,
  ] # string or list of strings
  sparses: hf-task-ds/Data/hSparseMass # string or list of strings
  event_histogram: lumi-task/hCounterTVXafterBCcuts

cut_set_file_name: path/to/cutset.yml

max_workers: 10

output:
  directory: path/of/output/dir
  file_names: [
    data.root,
  ]
